@extends('base')
@section('title', 'Главная')
@section('main')
@include("blocks.header")
@include("blocks.menu")
@include("blocks.hero")
@include("blocks.features")
@include("blocks.achievement")
@include("blocks.last_news")
@include("blocks.our_clients")
@include("blocks.footer")
@endsection('main')
