@section('title', 'Главная')
@extends('base')

@section('main')
@include("blocks.header")
@include("blocks.menu")
@include("blocks.hero")
@include("blocks.features")
@include("blocks.achievement")
@include("blocks.products")
{{--@include("blocks.our_clients")--}}
@include("blocks.last_news")
@include("blocks.map")
@include("blocks.footer")
@endsection('main')
